### ISSUE TITLE
Website down due to disk capacity limits

### ISSUE THREAD

**Issue by jugglinmike** [bocoup/mobilevis#28]
http://mobilev.is is currently incapable of serving requests for `main.js`. This is the entry point for the front-end application, so the website is effectively down.

The reason for this is that the hard disk has reached capacity:

    $ df -h
    Filesystem      Size  Used Avail Use% Mounted on
    /dev/xvda1      7.8G  7.4G     0 100% /
    none            4.0K     0  4.0K   0% /sys/fs/cgroup
    udev            240M   12K  240M   1% /dev
    tmpfs            49M  336K   49M   1% /run
    none            5.0M     0  5.0M   0% /run/lock
    none            245M     0  245M   0% /run/shm
    none            100M     0  100M   0% /run/user

This has occurred because the access logs are not being rotated as intended, and the logs are stored on the same partition as the application code:

    $ ls -lah /mnt/logs
    total 5.8G
    drwxr-xr-x 2 root     root 4.0K Apr 19  2016 .
    drwxr-xr-x 4 root     root 4.0K Apr 22  2016 ..
    -rwxr-xr-x 1 root     root    0 Apr 19  2016 api.log
    -rwxr-xr-x 1 www-data root 5.8G Dec 28 22:11 nginx-access.log
    -rwxr-xr-x 1 www-data root 1.3M Dec 28 22:10 nginx-error.log

**Comment by jugglinmike** [comment]
[The deployment scripts which are available on the latest commit in `master`](https://github.com/bocoup/mobilevis/tree/04af670def2b267c52fc1e6f14a9c530e7dfcc2e/deploy) don't appear to function in production settings. I've had to diagnose the problem by inspecting the state of the system directly. On that system, logrotate is configured to switch to the `ubuntu` user prior to rotating the log files:

    $ cat /etc/logrotate.d/mobilevis
    /mnt/logs/*.log {
      monthly
      su ubuntu
      missingok
      rotate 7
      size 50M
      compress
      delaycompress
      copytruncate
      notifempty
      create 644 ubuntu ubuntu
      mailfirst
      mail irene@bocoup.com
      maxage 30
      rotate 5
    }

However, as documented above, the logs are only writable by `root`. Here's a demonstration of the problem:

    $ sudo logrotate /etc/logrotate.d/mobilevis
    error: error opening /mnt/logs/nginx-access.log: Permission denied

Two possible fixes come to mind:

- change the permissions of the log files
- allow logrotate to run as root

The former seems preferable since it limits the involvement of the superuser, but that may have unintended effects on other parts of the system (e.g. whatever other processes write/read the log files). The latter fix has less margin for error. Since this application is not actively maintained, I'm preferring that.

I've made the change by editing the file in production directly (removing `su ubuntu`). That wasn't enough, though, because rotation can't occur when there is no available disk space. I truncated the log:

    $ sudo sed -i 1,31045319d nginx-access.log
    $ sudo service nginx restart
    $ df -h
    Filesystem      Size  Used Avail Use% Mounted on
    /dev/xvda1      7.8G  2.0G  5.5G  27% /
    none            4.0K     0  4.0K   0% /sys/fs/cgroup
    udev            240M   12K  240M   1% /dev
    tmpfs            49M  336K   49M   1% /run
    none            5.0M     0  5.0M   0% /run/lock
    none            245M     0  245M   0% /run/shm
    none            100M     0  100M   0% /run/user

And then manually invoked logrotate, confirming that things are now (mostly) working as expected:

    $ sudo logrotate /etc/logrotate.d/mobilevis
    error: mail command failed for /mnt/logs/nginx-access.log.1
    $ ls -lah /mnt/logs
    total 361M
    drwxr-xr-x 2 root     root 4.0K Dec 29 00:17 .
    drwxr-xr-x 4 root     root 4.0K Apr 22  2016 ..
    -rwxr-xr-x 1 root     root    0 Apr 19  2016 api.log
    -rwxr-xr-x 1 www-data root  941 Dec 29 00:17 nginx-access.log
    -rwxr-xr-x 1 www-data root 359M Dec 29 00:17 nginx-access.log.1
    -rwxr-xr-x 1 www-data root 1.3M Dec 29 00:15 nginx-error.log

(The mail failure is unrelated; I'm not sure this system was every properly configured to send e-mail.)

And with that, nginx is now able to serve `main,js`, and the website looks just as good as when it was last deployed.

[The `ansible` branch of this project has Ansible configuration files](https://github.com/bocoup/mobilevis/tree/ansible/deploy/ansible), and those seem to be much closer to reality. [I've added a commit that implements this change.](https://github.com/bocoup/mobilevis/commit/1045ffa39269cb690ab7c0c7699122f55032bf8d) That way, if anyone picks up development from there, this issue won't bite them. It's possible that development may pick up from some other branch, though, so I'll leave this issue open to help avoid regression.

**Comment by boazsender** [comment]
I believe this has been resolved. Closing.
